[env:raspberry-pi-pico]


board = pico
framework = arduino

; lib_ignore = SdFat - Adafruit Fork
build_flags = 

    -D PICO_DEFAULT_SPI=0
    -D PICO_DEFAULT_SPI_SCK_PIN=18
    -D PICO_DEFAULT_SPI_TX_PIN=19
    -D PICO_DEFAULT_SPI_RX_PIN=16
    -D PICO_DEFAULT_SPI_CSN_PIN=17


platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.core = earlephilhower